name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
    - name: Commit changes
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR_NAME: ${{ github.actor }}
        GITHUB_REPOSITORY_NAME: ${{ github.repository }}
        GITHUB_HEAD_REF: ${{ github.head_ref }}
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "fix: pre-commit fixes by $GITHUB_ACTOR_NAME"
        git push "https://$GITHUB_ACTOR_NAME:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY_NAME.git" "HEAD:$GITHUB_HEAD_REF"
